import { Injectable, OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit {
  constructor(configService: ConfigService) {
    const connectionString = configService.get<string>('DATABASE_URL');
    const pool = new Pool({ connectionString });
    const adapter = new PrismaPg(pool);
    super({ adapter, log: [{ emit: 'event', level: 'query' }, { emit: 'event', level: 'error' }] });

    // Log Prisma query events to help debug SQL generated by client
    this.$on('query', (e: any) => {
      console.debug('Prisma query:', e.query, 'params:', e.params);
    });

    this.$on('error', (e: any) => {
      console.error('Prisma error event:', e);
    });
  }

  async onModuleInit() {
    await this.$connect();
  }
}
